openapi: 3.0.0
info:
  version: 0.1.0
  title: Auth Service
  description: Service to login and register in StackingUp network
  contact:
    name: StackingUp
    email: stackingup13@gmail.com
    url: 'https://stacking-up.github.io'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /api/v1/login:
    post:
      tags:
        - Authentication
      x-swagger-router-controller: AuthController
      description: Checks the credentials and generates JWT
      operationId: login
      requestBody:
        x-name: credentials
        description: Login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/credentials'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - email
                  - role
                  - userId
                properties:
                  email:
                    type: string
                  role:
                    type: string
                  userId:
                    type: integer
          headers:
            Set-Cookie:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  /api/v1/logout:
    post:
      tags:
        - Authentication
      x-swagger-router-controller: AuthController
      description: Logouts, removes JWT token
      operationId: logout
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
          headers:
            Set-Cookie:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  /api/v1/register:
    post:
      tags:
        - Authentication
      x-swagger-router-controller: AuthController
      description: Checks the user information and create a new user
      operationId: register
      requestBody:
        x-name: user
        description: User information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userRegister'
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'  
  /api/v1/verify:
    post:
      security:
        - cookieAuth: []
      tags:
        - Verification
      x-swagger-router-controller: AuthController
      description: Verifies the user phone number
      operationId: postVerify
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
    put:
      security:
        - cookieAuth: []
      tags:
        - Verification
      x-swagger-router-controller: AuthController
      description: Verifies the user phone number
      operationId: putVerify
      requestBody:
        x-name: code
        description: Random code sent to the user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/code'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/errorModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
  /api/v1/suscribe:
    put:
      security:
        - cookieAuth: []
      tags:
        - Subscription
      x-swagger-router-controller: AuthController
      description: Update the user role to SUBSCRIBED after the payment
      operationId: putSuscribed
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/errorModel'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'

components:
  schemas:
    errorModel:
      type: string
    credentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    userRegister:
      type: object
      required:
        - name
        - surname
        - email
        - password
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        password:
          type: string
    code:
      type: object
      required:
        - code
      properties:
        code:
          type: string

